"""add rf scene to jobs

Revision ID: 0cc998d63044
Revises: 0a6d6646d44d
Create Date: 2026-05-24 21:25:25.857299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc998d63044'
down_revision: Union[str, None] = '0a6d6646d44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('rf_scene_definition_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'rf_scene_definitions', ['rf_scene_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'rf_scene_definition_id')
    # ### end Alembic commands ###
